services:
  - type: web
    name: vasmo-agent
    runtime: docker
    dockerfilePath: agent/Dockerfile
    dockerContext: agent
    healthCheckPath: /health
    envVars:
      - key: RPC_URL
        value: https://sepolia.base.org
      - key: WS_PORT
        value: "8080"
      - key: INVOICE_NFT_ADDRESS
        value: "0x515ab226DD7917612eeDd439A9Cfb0b4b1731440"
      - key: YIELD_VAULT_ADDRESS
        value: "0xacBeB5f58604A4A9A8B9a74EC39ebCA1117bC326"
      - key: AGENT_ROUTER_ADDRESS
        value: "0xEe9AD131A155E7669004056F01fFb26964637Fd4"
      - key: PYTH_ORACLE_ADDRESS
        value: "0xA0E9510fBe1Ee857B255B2960438122fdA0b32E3"
      - key: AAVE_YIELD_ADDRESS
        value: "0x447De96C1c3E15af485a41fb1B5Fde888B02d9eF"
      - key: AGENT_PRIVATE_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
